# Generated by Django 2.2.1 on 2019-07-19 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests', '0015_testorder_validation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_report', models.FileField(upload_to='reports')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('category', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.TestOrder')),
            ],
        ),
    ]
