# Generated by Django 2.2.1 on 2019-07-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_processing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentvalidation',
            old_name='category',
            new_name='approved_order',
        ),
        migrations.AlterField(
            model_name='paymentvalidation',
            name='upload_report',
            field=models.FileField(upload_to='reports_PDF'),
        ),
    ]
