# Generated by Django 2.2.1 on 2019-07-20 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_processing', '0002_auto_20190719_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentvalidation',
            options={'ordering': ['-id']},
        ),
    ]
