# Generated by Django 2.2.1 on 2019-07-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_processing', '0003_auto_20190720_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvalidation',
            name='send_message',
            field=models.CharField(default='default message', max_length=250),
            preserve_default=False,
        ),
    ]
