# Generated by Django 2.2.1 on 2019-08-17 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_processing', '0005_auto_20190728_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentvalidation',
            name='approved_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.TestOrder'),
        ),
    ]
