# Generated by Django 2.2.1 on 2019-05-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(default='default_center.jpg', upload_to='diagnostic_center_pics')),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Diagnostic Centers',
            },
        ),
    ]
