# Generated by Django 2.2.1 on 2019-05-24 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic_centers', '0002_auto_20190524_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(default='456', max_length=100)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_staffs', to='diagnostic_centers.DiagnosticCenter')),
            ],
            options={
                'verbose_name_plural': 'Diagnostic Staffs',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(default='123', max_length=100)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_admins', to='diagnostic_centers.DiagnosticCenter')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_admins', to='diagnostic_centers.DiagnosticStaff')),
            ],
            options={
                'verbose_name_plural': 'Diagnostic Admins',
            },
        ),
    ]
