# Generated by Django 2.2.1 on 2019-05-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic_centers', '0003_diagnosticadmin_diagnosticstaff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosticcenter',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Diagnostic Centers'},
        ),
        migrations.AlterField(
            model_name='diagnosticadmin',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosticstaff',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
