# Generated by Django 2.2.1 on 2019-06-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic_centers', '0005_auto_20190526_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticadmin',
            name='ss',
            field=models.ManyToManyField(blank=True, to='diagnostic_centers.DiagnosticStaff'),
        ),
    ]
