# Generated by Django 2.2.1 on 2019-06-18 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic_centers', '0006_diagnosticadmin_ss'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticstaff',
            name='reported_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_admin', to='diagnostic_centers.DiagnosticAdmin'),
        ),
    ]
