# Generated by Django 2.2.1 on 2019-06-18 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic_centers', '0007_diagnosticstaff_reported_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticadmin',
            name='ss',
        ),
        migrations.RemoveField(
            model_name='diagnosticstaff',
            name='reported_to',
        ),
    ]
