# Generated by Django 2.2.1 on 2019-08-05 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic_centers', '0008_diagnosticadmin_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosticcenter',
            options={'verbose_name_plural': 'Diagnostic Centers'},
        ),
    ]
