# Generated by Django 2.2.1 on 2019-06-18 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic_centers', '0009_auto_20190619_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticstaff',
            name='reported_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnostic_centers.DiagnosticAdmin'),
        ),
    ]
