# Generated by Django 2.2.1 on 2019-06-18 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic_centers', '0010_diagnosticstaff_reported_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticstaff',
            name='reported_to',
        ),
    ]
