# Generated by Django 2.2.1 on 2019-07-13 11:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic_centers', '0008_diagnosticadmin_admin'),
        ('tests', '0012_auto_20190706_2256'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reports',
        ),
        migrations.AlterModelOptions(
            name='ordervalidation',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='ordervalidation',
            name='admin',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='diagnostic_centers.DiagnosticAdmin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordervalidation',
            name='approved_orders',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='tests.TestOrder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordervalidation',
            name='confirmation_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ordervalidation',
            name='confirmed_by_staff',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordervalidation',
            name='payment_status',
            field=models.CharField(choices=[('Full Payment Complete', 'Full Payment Complete'), ('Payment NOT Complete', 'Payment NOT Complete')], default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordervalidation',
            name='staff',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='diagnostic_centers.DiagnosticStaff'),
            preserve_default=False,
        ),
    ]
