# Generated by Django 2.2.1 on 2019-07-13 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20190713_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordervalidation',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='diagnostic_centers.DiagnosticAdmin'),
        ),
        migrations.AlterField(
            model_name='ordervalidation',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='diagnostic_centers.DiagnosticStaff'),
        ),
    ]
