# Generated by Django 2.2.1 on 2019-05-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_name',
            field=models.CharField(default='default', max_length=250),
            preserve_default=False,
        ),
    ]
