# Generated by Django 2.2.1 on 2019-07-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0004_auto_20190622_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
