# Generated by Django 2.2.1 on 2019-06-22 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnostic_centers', '0006_auto_20190620_1802'),
        ('custom_users', '0003_profile_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=250)),
                ('image', models.ImageField(default='default_test.jpg', upload_to='test_pics')),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('active_status', models.CharField(choices=[('Available', 'AVAILABLE'), ('Closed', 'CLOSED')], default='AVAILABLE', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Tests',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Test Categories',
            },
        ),
        migrations.CreateModel(
            name='TetOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_option', models.CharField(choices=[('Full Payment', 'FULL'), ('Half Payment', 'HALF'), ('On Spot', 'SPOT')], max_length=20)),
                ('date_time', models.DateTimeField()),
                ('client_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_user_order', to='custom_users.Profile')),
                ('test_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_order', to='tests.Test')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_category', to='tests.TestCategory'),
        ),
        migrations.AddField(
            model_name='test',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_center', to='diagnostic_centers.DiagnosticCenter'),
        ),
    ]
