# Generated by Django 2.2.1 on 2019-06-22 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0003_profile_address'),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TetOrder',
            new_name='TestOrder',
        ),
    ]
