# Generated by Django 2.2.1 on 2019-06-22 02:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20190622_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testorder',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
