# Generated by Django 2.2.1 on 2019-06-22 02:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20190622_0824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testorder',
            old_name='date_time',
            new_name='date',
        ),
        migrations.AddField(
            model_name='testorder',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
