# Generated by Django 2.2.1 on 2019-06-22 02:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_auto_20190622_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testorder',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
