# Generated by Django 2.2.1 on 2019-06-22 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_auto_20190622_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='testorder',
            name='admin_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testorder',
            name='staff_check',
            field=models.BooleanField(default=False),
        ),
    ]
