# Generated by Django 2.2.1 on 2019-06-22 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_auto_20190622_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='testorder',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
