# Generated by Django 2.2.1 on 2019-06-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_testorder_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='testorder',
            name='contact_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
