# Generated by Django 2.2.1 on 2019-06-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_auto_20190623_0122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testorder',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Test Orders'},
        ),
        migrations.AddField(
            model_name='testorder',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='testorder',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
