# Generated by Django 2.2.1 on 2019-07-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_auto_20190625_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testorder',
            old_name='time',
            new_name='order_created_at',
        ),
        migrations.RemoveField(
            model_name='testorder',
            name='date',
        ),
        migrations.RemoveField(
            model_name='testorder',
            name='payment_option',
        ),
        migrations.AddField(
            model_name='testorder',
            name='booked_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testorder',
            name='booked_time_slot',
            field=models.CharField(blank=True, choices=[('10:00 AM - 2:00 PM', '10:00 AM - 2:00 PM'), ('3:00 PM - 7:00 PM', '3:00 PM - 7:00 PM'), ('8:00 PM - 10:00 PM', '8:00 PM - 10:00 PM')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='testorder',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('BKASH', 'Bkash'), ('CREDIT CARD', 'Credit Card'), ('ON SPOT', 'On Spot')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='testorder',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Full Payment', 'Full Payment'), ('Half Payment', 'Half Payment')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
