# Generated by Django 2.2.1 on 2019-06-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_auto_20190625_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testorder',
            name='payment_option',
            field=models.CharField(choices=[('Full Payment', 'Full Payment'), ('Half Payment', 'Half Payment')], max_length=20),
        ),
    ]
