# Generated by Django 2.2.1 on 2019-07-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_auto_20190706_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testorder',
            name='order_created_at',
            field=models.TimeField(auto_now=True),
        ),
    ]
