# Generated by Django 2.2.1 on 2019-06-27 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_auto_20190626_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testorder',
            old_name='payment_option',
            new_name='payment_type',
        ),
    ]
