# Generated by Django 2.2.1 on 2019-07-19 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_auto_20190706_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testorder',
            name='client_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='test_user_order', to='custom_users.Profile'),
        ),
        migrations.AlterField(
            model_name='testorder',
            name='test_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='test_order', to='tests.Test'),
        ),
    ]
