# Generated by Django 2.2.1 on 2019-07-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0014_auto_20190719_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='testorder',
            name='validation',
            field=models.BooleanField(default=False),
        ),
    ]
