# Generated by Django 2.2.1 on 2019-07-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0016_testorder_order_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='testorder',
            name='came_for_test',
            field=models.BooleanField(default=False),
        ),
    ]
