# Generated by Django 2.2.1 on 2019-08-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0017_testorder_came_for_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testorder',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Full Payment', 'Full Payment'), ('Half Payment', 'Half Payment')], default='Full Payment', max_length=20, null=True),
        ),
    ]
