# Generated by Django 2.2.1 on 2019-08-05 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic_centers', '0009_auto_20190805_2329'),
        ('tests', '0018_auto_20190803_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcategory',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_center', to='diagnostic_centers.DiagnosticCenter'),
        ),
    ]
